# Generated by Django 2.2 on 2020-03-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='age_of_voters',
            field=models.IntegerField(default=16),
        ),
    ]
